name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_lines: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs, editors
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_notable: yes
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
